### ISSUE TITLE
Parameter Store does not exist

### ISSUE THREAD

**Issue by Rubyj** [tripleonard/wireguard-cloudformation#2]
I have used this template a bunch in the past, but I have noticed now when I use it, the cloud formation output points to a non-existing parameter in the parameter store. It seems that the parameter is not properly being created @tripleonard is this something you can help with?

**Comment by Rubyj** [comment]
Correction - seems to work in us-east-1/2 but not us-west-2

**Comment by daz10000** [comment]
One note - when I first ran this, I saw exactly that - no parameters pushed to SSM in `us-west-2`.  While troubleshooting, I added in a few things to make it easier to debug (added a keypair and opened ssh for admin) and ran it again and it worked the second time - pushed parameters correctly.  Don't know if that was luck or trying twice.   I increased instance size on second run.  The first time I wasn't sure if it had rebooted or not, so I manually rebooted.  Maybe I was too impatient and it was still updating.

**Comment by Rubyj** [comment]
@daz10000 interesting. I have only noticed this problem intermittently. When you say ran again - do you mean you ran the terraform create stack again?

**Comment by daz10000** [comment]
I made some small changes to the cloud formation script (added in a keypair and started sshd), deleted the stack and built it again and the second time I was expecting to have to get on the instance and troubleshoot but it just worked.

**Comment by tripleonard** [comment]
Sorry for the delay here. I have not looked at this in a while :) There are some shenanigans here, for wireguard to start the EC2 is forced to reboot, then after reboot it generates and places the SSM Parameter. It takes about 5 minutes after the cloudformation says complete.  It should be in the region where the cfn is executed.

https://github.com/tripleonard/wireguard-cloudformation/blob/0a6b63a02a5ad9e9d2be108eb1efe301ab24d9f0/wireguard.json#L204

Cheers!

**Comment by tripleonard** [comment]
I can't repo this, so I am going to close this issue.
